export const createPost = async (..._args: any[]) => null as any;
export const getCurrentUser = async (..._args: any[]) => null as any;
export const getPostById = async (..._args: any[]) => null as any;
export const getRecentPosts = async (..._args: any[]) => null as any;
export const getUserById = async (..._args: any[]) => null as any;
export const getUserPosts = async (..._args: any[]) => null as any;
export const getFollowingFeed = async (..._args: any[]) => null as any;
export const likePost = async (..._args: any[]) => null as any;
export const deleteLike = async (..._args: any[]) => null as any;
export const savePost = async (..._args: any[]) => null as any;
export const deleteSave = async (..._args: any[]) => null as any;
export const getSavedPosts = async (..._args: any[]) => null as any;
export const getLikedPosts = async (..._args: any[]) => null as any;
export const signInUser = async (..._args: any[]) => null as any;
export const signOutUser = async (..._args: any[]) => null as any;
export const signUpUser = async (..._args: any[]) => null as any;
export const updatePost = async (..._args: any[]) => null as any;
export const updateUser = async (..._args: any[]) => null as any;
export const deletePost = async (..._args: any[]) => null as any;
export const getUsers = async (..._args: any[]) => null as any;
export const searchPosts = async (..._args: any[]) => null as any;
export const getPublicUserById = async (..._args: any[]) => null as any;
export const getPublicUserPosts = async (..._args: any[]) => null as any;
export const getPublicFollowersCount = async (..._args: any[]) => null as any;
export const getPublicFollowingCount = async (..._args: any[]) => null as any;
export const getPublicPostById = async (..._args: any[]) => null as any;
export const getInfinitePosts = async (..._args: any[]) => null as any;
export const followUser = async (..._args: any[]) => null as any;
export const unfollowUser = async (..._args: any[]) => null as any;
export const getFollowersCount = async (..._args: any[]) => null as any;
export const getFollowingCount = async (..._args: any[]) => null as any;
export const isFollowing = async (..._args: any[]) => null as any;
export const getFollowers = async (..._args: any[]) => null as any;
export const getFollowing = async (..._args: any[]) => null as any;
export const getAdminStats = async (..._args: any[]) => ({
    totalUsers: 0,
    totalPosts: 0,
    totalLikes: 0,
    activeUsers: 0
});
export const checkAdminAccess = async (..._args: any[]) => false;
export const getAdminUsers = async (..._args: any[]) => null as any;
export const addAdminUser = async (..._args: any[]) => null as any;
export const removeAdminUser = async (..._args: any[]) => null as any;
export const sendPasswordResetEmail = async (..._args: any[]) => null as any;
export const updateUserPassword = async (..._args: any[]) => null as any;
export const createComment = async (..._args: any[]) => null as any;
export const getPostComments = async (..._args: any[]) => null as any;
export const updateComment = async (..._args: any[]) => null as any;
export const deleteComment = async (..._args: any[]) => null as any;
export const searchUsers = async (..._args: any[]) => null as any;
export const getAdminAllUsers = async (..._args: any[]) => null as any;
export const getAdminUserDetails = async (..._args: any[]) => null as any;
export const deactivateUser = async (..._args: any[]) => null as any;
export const toggleUserActivation = async (..._args: any[]) => null as any;
export const getAdminAllPosts = async (..._args: any[]) => null as any;
export const adminDeletePost = async (..._args: any[]) => null as any;
export const getCommentLikeStatus = async (..._args: any[]) => false;
export const likeComment = async (..._args: any[]) => true;
export const unlikeComment = async (..._args: any[]) => true;
